CREATE TABLE IF NOT EXISTS todos (
    id SERIAL PRIMARY KEY,
    creation_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    summary VARCHAR(128) NOT NULL,
    task VARCHAR(2048) NOT NULL,
    due_time TIMESTAMP WITH TIME ZONE
);