CREATE TABLE IF NOT EXISTS todos (
    id SERIAL PRIMARY KEY,
    creation_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    summary VARCHAR(255) NOT NULL,
    task TEXT NOT NULL,
    due_time TIMESTAMP WITH TIME ZONE,
    completed BOOLEAN NOT NULL DEFAULT FALSE
);